services:
    collector:
        build:
            context: .
            dockerfile: Dockerfile.collector
        image: collector
        ports:
            - "50051:50051"

    gateway:
        build:
            context: .
            dockerfile: Dockerfile.gateway
        image: gateway
        ports:
            - "8080:8080"
        depends_on:
            - collector
