services:
    collector:
        build:
            context: .
            dockerfile: Dockerfile.collector
        environment:
            COLLECTOR_PORT: "50052"
        image: collector
        ports:
            - "50052:50052"

    gateway:
        build:
            context: .
            dockerfile: Dockerfile.gateway
        environment:
            PROCESSOR_ADDR: "processor:50051"
            COLLECTOR_ADDR: "collector:50052"
            SUBSCRIBER_ADDR: "subscriber:50053"
            GATEWAY_PORT: "8080"
        image: gateway
        ports:
            - "8080:8080"
        depends_on:
            - processor
            - collector
            - subscriber

    processor:
        build:
            context: .
            dockerfile: Dockerfile.processor
        environment:
            COLLECTOR_ADDR: "collector:50052"
            PROCESSOR_PORT: "50051"
        image: processor
        ports:
            - "50051:50051"
        depends_on:
            - collector

    subscriber:
        build:
            context: .
            dockerfile: Dockerfile.subscriber
        environment:
            SUBSCRIBER_PORT: "50053"
            DB_DSN: "postgres://postgres:postgres@postgres:5432/subscribers?sslmode=disable"
        image: subscriber
        ports:
            - "50053:50053"
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:17-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: subscribers
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d subscribers"]
            interval: 5s
            timeout: 3s
            retries: 5

    migrate:
        image: migrate/migrate:v4.19.1
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./migrations:/migrations:ro,Z
        command:
            [
                "-path",
                "/migrations",
                "-database",
                "postgres://postgres:postgres@postgres:5432/subscribers?sslmode=disable",
                "up",
            ]

volumes:
    postgres_data:
