services:
    collector:
        build:
            context: .
            dockerfile: Dockerfile.collector
        environment:
            COLLECTOR_PORT: "50051"
        image: collector
        ports:
            - "50051:50051"

    gateway:
        build:
            context: .
            dockerfile: Dockerfile.gateway
        environment:
            COLLECTOR_ADDR: "collector:50051"
            GATEWAY_PORT: "8080"
        image: gateway
        ports:
            - "8080:8080"
        depends_on:
            - collector
