// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package processor

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Repository struct {
	ID          int64
	Owner       string
	Repo        string
	Description string
	Stars       int32
	Forks       int32
	CreatedAt   pgtype.Timestamptz
	AddedAt     pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
