// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package processor

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
  owner, repo, description, stars, forks, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, owner, repo, description, stars, forks, created_at, added_at, updated_at
`

type CreateRepositoryParams struct {
	Owner       string
	Repo        string
	Description string
	Stars       int32
	Forks       int32
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.Owner,
		arg.Repo,
		arg.Description,
		arg.Stars,
		arg.Forks,
		arg.CreatedAt,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.Description,
		&i.Stars,
		&i.Forks,
		&i.CreatedAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM repositories
WHERE owner = $1 AND repo = $2
`

type DeleteSubscriptionParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.Owner, arg.Repo)
	return err
}

const getRepositories = `-- name: GetRepositories :many
SELECT id, owner, repo, description, stars, forks, created_at, added_at, updated_at FROM repositories
`

func (q *Queries) GetRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, getRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.Description,
			&i.Stars,
			&i.Forks,
			&i.CreatedAt,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isExistsRepository = `-- name: IsExistsRepository :one
SELECT EXISTS(
    SELECT 1 FROM repositories
    WHERE owner = $1 AND repo = $2
)
`

type IsExistsRepositoryParams struct {
	Owner string
	Repo  string
}

func (q *Queries) IsExistsRepository(ctx context.Context, arg IsExistsRepositoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExistsRepository, arg.Owner, arg.Repo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
