// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package subscriber

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID        int64
	Owner     string
	Repo      string
	CreatedAt pgtype.Timestamptz
}
