// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package subscriber

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  owner, repo
) VALUES (
  $1, $2
)
RETURNING id, owner, repo, created_at
`

type CreateSubscriptionParams struct {
	Owner string
	Repo  string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.Owner, arg.Repo)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Repo,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE owner = $1 AND repo = $2
`

type DeleteSubscriptionParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.Owner, arg.Repo)
	return err
}

const getSubscriptions = `-- name: GetSubscriptions :many
SELECT id, owner, repo, created_at FROM subscriptions
`

func (q *Queries) GetSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Repo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isExistsSubscription = `-- name: IsExistsSubscription :one
SELECT EXISTS(
    SELECT 1 FROM subscriptions
    WHERE owner = $1 AND repo = $2
)
`

type IsExistsSubscriptionParams struct {
	Owner string
	Repo  string
}

func (q *Queries) IsExistsSubscription(ctx context.Context, arg IsExistsSubscriptionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExistsSubscription, arg.Owner, arg.Repo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
