// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Xamelllion",
            "url": "t.me/xamelllion",
            "email": "me@xamelllion.ru"
        },
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org/"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ping": {
            "get": {
                "description": "get status of services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Get status of services",
                "operationId": "get-status-of-services",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ServicesInfo"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/domain.ServicesInfo"
                        }
                    }
                }
            }
        },
        "/repo/{owner}/{repo}": {
            "get": {
                "description": "get repo by owner\\repo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repo"
                ],
                "summary": "Get repository by owner and repo name",
                "operationId": "get-repo-by-owner-repo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Repo name",
                        "name": "repo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Owner name",
                        "name": "owner",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Repository"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controller.GetRepository.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.GetRepository.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controller.GetRepository.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.GetRepository.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "some error"
                }
            }
        },
        "domain.PingStatus": {
            "type": "string",
            "enum": [
                "up",
                "down"
            ],
            "x-enum-varnames": [
                "PingStatusUp",
                "PingStatusDown"
            ]
        },
        "domain.Repository": {
            "type": "object",
            "properties": {
                "create_date": {
                    "type": "string",
                    "example": "2026-03-03T16:45:04Z"
                },
                "description": {
                    "type": "string",
                    "example": "xamelllion's repo"
                },
                "forks": {
                    "type": "integer",
                    "example": 2
                },
                "name": {
                    "type": "string",
                    "example": "xamelllion"
                },
                "stars": {
                    "type": "integer",
                    "example": 122
                }
            }
        },
        "domain.ServiceStatus": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.PingStatus"
                }
            }
        },
        "domain.ServicesInfo": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ServiceStatus"
                    }
                },
                "status": {
                    "$ref": "#/definitions/domain.ServicesStatus"
                }
            }
        },
        "domain.ServicesStatus": {
            "type": "string",
            "enum": [
                "ok",
                "degraded"
            ],
            "x-enum-varnames": [
                "ServicesStatusOk",
                "ServicesStatusDegraded"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TestApp API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
