basePath: /
definitions:
  controller.GetRepository.HTTPError:
    properties:
      error:
        example: some error
        type: string
    type: object
  domain.PingStatus:
    enum:
    - up
    - down
    type: string
    x-enum-varnames:
    - PingStatusUp
    - PingStatusDown
  domain.Repository:
    properties:
      create_date:
        example: "2026-03-03T16:45:04Z"
        type: string
      description:
        example: xamelllion's repo
        type: string
      forks:
        example: 2
        type: integer
      name:
        example: xamelllion
        type: string
      stars:
        example: 122
        type: integer
    type: object
  domain.ServiceStatus:
    properties:
      name:
        type: string
      status:
        $ref: '#/definitions/domain.PingStatus'
    type: object
  domain.ServicesInfo:
    properties:
      services:
        items:
          $ref: '#/definitions/domain.ServiceStatus'
        type: array
      status:
        $ref: '#/definitions/domain.ServicesStatus'
    type: object
  domain.ServicesStatus:
    enum:
    - ok
    - degraded
    type: string
    x-enum-varnames:
    - ServicesStatusOk
    - ServicesStatusDegraded
host: localhost:8080
info:
  contact:
    email: me@xamelllion.ru
    name: Xamelllion
    url: t.me/xamelllion
  license:
    name: MIT
    url: https://mit-license.org/
  title: TestApp API
  version: "0.1"
paths:
  /api/ping:
    get:
      consumes:
      - application/json
      description: get status of services
      operationId: get-status-of-services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ServicesInfo'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/domain.ServicesInfo'
      summary: Get status of services
      tags:
      - service
  /repo/{owner}/{repo}:
    get:
      consumes:
      - application/json
      description: get repo by owner\repo
      operationId: get-repo-by-owner-repo
      parameters:
      - description: Repo name
        in: path
        name: repo
        required: true
        type: string
      - description: Owner name
        in: path
        name: owner
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Repository'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
      summary: Get repository by owner and repo name
      tags:
      - repo
swagger: "2.0"
