basePath: /
definitions:
  controller.GetRepository.HTTPError:
    properties:
      error:
        example: some error
        type: string
    type: object
  controller.SubscribeRequest:
    properties:
      owner:
        example: octocat
        type: string
      repo:
        example: Hello-World
        type: string
    type: object
  domain.PingStatus:
    enum:
    - up
    - down
    type: string
    x-enum-varnames:
    - PingStatusUp
    - PingStatusDown
  domain.Repository:
    properties:
      create_date:
        example: "2026-03-03T16:45:04Z"
        type: string
      description:
        example: xamelllion's repo
        type: string
      forks:
        example: 2
        type: integer
      name:
        example: xamelllion
        type: string
      stars:
        example: 122
        type: integer
    type: object
  domain.ServiceStatus:
    properties:
      name:
        type: string
      status:
        $ref: '#/definitions/domain.PingStatus'
    type: object
  domain.ServicesInfo:
    properties:
      services:
        items:
          $ref: '#/definitions/domain.ServiceStatus'
        type: array
      status:
        $ref: '#/definitions/domain.ServicesStatus'
    type: object
  domain.ServicesStatus:
    enum:
    - ok
    - degraded
    type: string
    x-enum-varnames:
    - ServicesStatusOk
    - ServicesStatusDegraded
  domain.Subscription:
    properties:
      owner:
        example: octocat
        type: string
      repo:
        example: Hello-World
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: me@xamelllion.ru
    name: Xamelllion
    url: t.me/xamelllion
  license:
    name: MIT
    url: https://mit-license.org/
  title: TestApp API
  version: "0.1"
paths:
  /api/ping:
    get:
      consumes:
      - application/json
      description: get status of services
      operationId: get-status-of-services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ServicesInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/domain.ServicesInfo'
      summary: Get status of services
      tags:
      - service
  /api/repositories/info:
    get:
      consumes:
      - application/json
      description: get repository information by GitHub repository URL
      operationId: get-repo-by-owner-repo
      parameters:
      - description: GitHub repository URL
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Repository'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
      summary: Get repository by GitHub URL
      tags:
      - repo
  /api/subscriptions:
    get:
      description: Get all repository subscriptions
      operationId: get-subscriptions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Subscription'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
      summary: Get subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Create a subscription to an existing GitHub repository
      operationId: subscribe-to-repository
      parameters:
      - description: Repository subscription
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/controller.SubscribeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
      summary: Subscribe to a repository
      tags:
      - subscriptions
  /api/subscriptions/{owner}/{repo}:
    delete:
      description: Delete an existing repository subscription
      operationId: unsubscribe-from-repository
      parameters:
      - description: GitHub repository owner
        example: octocat
        in: path
        name: owner
        required: true
        type: string
      - description: GitHub repository name
        example: Hello-World
        in: path
        name: repo
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
      summary: Unsubscribe from a repository
      tags:
      - subscriptions
  /api/subscriptions/info:
    get:
      description: Get GitHub information for every subscribed repository
      operationId: get-subscribed-repository-info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Repository'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/controller.GetRepository.HTTPError'
      summary: Get subscribed repository information
      tags:
      - subscriptions
swagger: "2.0"
